FROM tsl0922/ttyd:latest
RUN apt-get update -qq && apt-get install -y --no-install-recommends docker.io && rm -rf /var/lib/apt/lists/*
COPY exec_container.sh /exec_container.sh
RUN chmod +x /exec_container.sh
EXPOSE 7681
CMD ["ttyd",      "--port", "7681",      "--max-clients", "10",      "--writable",      "--permit-arguments",      "-t", "titleFixed=Container Terminal",      "-t", "rendererType=canvas",      "-t", "fontSize=14",      "/exec_container.sh"]
