log:
  level: info

store:
  type: "postgres"
  postgres:
    dsn: "postgres://litellm:litellm_password@postgres:5432/zep?sslmode=disable"

auth:
  required: false
  secret: ""

server:
  port: 8000

llm:
  anthropic_api_key: ""
  openai:
    endpoint: "http://litellm:4000"
    api_key: "sk-sa-prod-ce5d031e2a50ffa45d3a200c037971f81853e27ed19b894bc3630625cba0b71a"
