#!/usr/bin/env bash
# vault-env.sh — fetch secrets from Vault and write .env.prod
set -euo pipefail

VAULT_ADDR="${VAULT_ADDR:-http://localhost:8200}"
KEYS_FILE="/root/.vault-keys"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_DIR/.env.prod"
SECRET_PATH="sdlc/prod"

[[ ! -f "$KEYS_FILE" ]] && { echo "[vault-env] ERROR: $KEYS_FILE not found."; exit 1; }
source "$KEYS_FILE"
VAULT_ADDR="${VAULT_ADDR:-http://localhost:8200}"

# Auto-unseal if needed
STATUS=$(curl -s "$VAULT_ADDR/v1/sys/health" | python3 -c "import json,sys; d=json.load(sys.stdin); print(\"sealed\" if d.get(\"sealed\") else \"ok\")" 2>/dev/null || echo "unreachable")
[[ "$STATUS" == "sealed" ]] && bash "$(dirname "${BASH_SOURCE[0]}")/vault-unseal.sh"
[[ "$STATUS" == "unreachable" ]] && { echo "[vault-env] ERROR: Vault unreachable"; exit 1; }

# Authenticate via AppRole
if [[ -n "${VAULT_ROLE_ID:-}" && -n "${VAULT_SECRET_ID:-}" ]]; then
    echo "[vault-env] Authenticating via AppRole..."
    VAULT_TOKEN=$(curl -sf -X POST "$VAULT_ADDR/v1/auth/approle/login" \
        -H "Content-Type: application/json" \
        -d "{\"role_id\": \"$VAULT_ROLE_ID\", \"secret_id\": \"$VAULT_SECRET_ID\"}" \
        | python3 -c "import json,sys; print(json.load(sys.stdin)[\"auth\"][\"client_token\"])")
else
    echo "[vault-env] WARNING: No AppRole — using root token."
    VAULT_TOKEN="$VAULT_ROOT_TOKEN"
fi

echo "[vault-env] Fetching secret/data/$SECRET_PATH..."
REAL_ENV=$(readlink -f "$ENV_FILE" 2>/dev/null || echo "$ENV_FILE")
BACKUP="${REAL_ENV}.bak.$(date +%Y%m%d_%H%M%S)"
[[ -f "$REAL_ENV" ]] && cp "$REAL_ENV" "$BACKUP"

curl -sf "$VAULT_ADDR/v1/secret/data/$SECRET_PATH" \
    -H "X-Vault-Token: $VAULT_TOKEN" \
    -o /tmp/vault_secret.json

python3 - /tmp/vault_secret.json "$REAL_ENV" << PYEOF
import json, sys

secret_file = sys.argv[1]
env_file    = sys.argv[2]

with open(secret_file) as f:
    data = json.load(f)

secrets  = data["data"]["data"]
version  = data["data"]["metadata"]["version"]
created  = data["data"]["metadata"]["created_time"]
key_count = len(secrets)

lines = [
    f"# Generated by vault-env.sh from HashiCorp Vault",
    f"# Path: secret/data/sdlc/prod  |  Version: {version}  |  Created: {created}",
    f"# DO NOT EDIT MANUALLY — update via vault-rotate.sh or vault-push.sh",
    "",
]
for k, v in sorted(secrets.items()):
    lines.append(f"{k}={v}")

with open(env_file, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"[vault-env] ✓ Written {key_count} keys (v{version}) to {env_file}")
PYEOF

chmod 600 "$REAL_ENV"
rm -f /tmp/vault_secret.json

# Verify written version matches latest Vault version
WRITTEN_VER=$(head -2 "$REAL_ENV" | grep -oP 'Version: \K\d+')
echo "[vault-env] Vault version written: v${WRITTEN_VER}"
echo "[vault-env] Backup: $BACKUP"
